port: <%= process.env.PORT %>
database:
  host: <%= process.env.DB_HOST %>
  username: <%= process.env.DB_USER %>
  password: <%= process.env.DB_PASS %>
wifi:
  ssid: <%= process.env.WIFI_SSID %>
  password: <% process.env.WIFI_PASSWORD %>
